# 서버 설정
server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: UTF-8  
#뷰resolver설정
spring:
  mvc:
    view:
      prefix: /WEB-INF/board/
      suffix: .jsp
      
# DataSource 설정
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: scott
    url: jdbc:oracle:thin:@localhost:1521:xe
    password: tiger
